package com.onghub.api.exception;

public enum ErrorCode {
    INVALID_CREDENTIALS,
    TOKEN_EXPIRED,
    RESOURCE_NOT_FOUND,
    DUPLICATE_ENTRY,
    VALIDATION_ERROR,
    INSUFFICIENT_PERMISSIONS,
    INVALID_STATUS_TRANSITION,
    INTERNAL_ERROR
}
